<a href="https://colab.research.google.com/github/shakyarujan/Deep-Learning-with-PyTorch/blob/master/Deep_Learning_Neural_Network_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [0]:
# Define Activation Function
def activationFunction(x):
  return 1/(1 + torch.exp(-x))

In [0]:
# Generate Some Data
torch.manual_seed(7)

# Features ( 5 random normal variables)
features = torch.randn((1,5))

# Random Weights for 5 features variables
weights = torch.randn_like(features)

# Define the bias 
bias = torch.randn((1,1))


In [0]:
# Generate the otput from given data
output = activationFunction((features * weights).sum() + bias)

In [0]:
print(output)

tensor([[0.1595]])


In [0]:
# Calculating with matrix multipication by changing the shape of weights
# weights.reshape() - reshape the matrix structure 
# weights.resize() - change the size by cloning the previous declear size
# weights.view() - Cloning the same size and shape of the declear weights 
new_weights = weights.view(5,1)
print(weights)
output = activationFunction((torch.mm(features,new_weights)) + bias)
print(output)

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.1595]])


In [0]:
# Multi Neural Network
torch.manual_seed(7)

new_features = torch.randn((1,3))

# Define the size of each layers in our network
n_input = new_features.shape[1]  # Input units size must match the numbers of the input features
n_hidden = 2  # Number of hidden units
n_output = 1  # Number of output units 

# Weights for input to the hidden layers
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden to output layer
W2 = torch.randn(n_hidden, n_output)

# Bias for hidden layer and output layer
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))


In [0]:
O1 = activationFunction(torch.mm(new_features, W1) + B1)
O2 = activationFunction(torch.mm(O1, W2) + B2)

print(O1)
print(O2)

tensor([[0.6813, 0.4355]])
tensor([[0.3171]])
